### ISSUE TITLE
Reverse a string

### ISSUE THREAD

**Issue by Ananyaas** [DSC-Banasthali-Vidyapith/Engineering-Daze#14]

**Comment by prettylittleminds** [comment]
I'd like to work on this issue in C please assign it to me.

**Comment by Ananyaas** [comment]
You can start working on this issue. All the best!

**Comment by Aashishkushwaha** [comment]
Can I provide solution for this problem in python ?

**Comment by IshitaBisaria** [comment]
Hi, I want to work on this please assign it to me. Preferred language: C++

**Comment by ananya-singh7** [comment]
Hi, I want to provide a solution for this in Java, please assign this to me

**Comment by Ananyaas** [comment]
@ananya-singh7 you can work on this issue. All the best!

**Comment by IshitaBisaria** [comment]
I would like to work on this issue. Preferred language: C++

**Comment by IshitaBisaria** [comment]
Hi, I would like to work on this issue. Preferred language: C++
