### ISSUE TITLE
Pushing zeroes to the end of the array

### ISSUE THREAD

**Issue by Ananyaas** [DSC-Banasthali-Vidyapith/Engineering-Daze#46]
AIM : Given an array of random numbers, Push all the zero’s of a given array to the end of the array.
Input :  arr[] = {1, 2, 0, 4, 3, 0, 5, 0};
Output : arr[] = {1, 2, 4, 3, 5, 0, 0, 0};

**Comment by pranjalg13** [comment]
Hey @Ananyaas , pushed the PR can you please check once.
